This category contains various armor sets which provide special effects and boosts.

## Table of contents
* [Ender Helmet](https://github.com/Slimefun/Slimefun4/wiki/Ender-Helmet)
* [Ender Chestplate](https://github.com/Slimefun/Slimefun4/wiki/Ender-Chestplate)
* [Ender Leggings](https://github.com/Slimefun/Slimefun4/wiki/Ender-Leggings)
* [Ender Boots](https://github.com/Slimefun/Slimefun4/wiki/Ender-Boots)
* [Slime Helmet](https://github.com/Slimefun/Slimefun4/wiki/Slime-Helmet)
* [Slime Chestplate](https://github.com/Slimefun/Slimefun4/wiki/Slime-Chestplate)
* [Slime Leggings](https://github.com/Slimefun/Slimefun4/wiki/Slime-Leggings)
* [Slime Boots](https://github.com/Slimefun/Slimefun4/wiki/Slime-Boots)
* [GlowStone Helmet](https://github.com/Slimefun/Slimefun4/wiki/GlowStone-Helmet)
* [GlowStone Chestplate](https://github.com/Slimefun/Slimefun4/wiki/GlowStone-Chestplate)
* [GlowStone Leggings](https://github.com/Slimefun/Slimefun4/wiki/GlowStone-Leggings)
* [GlowStone Boots](https://github.com/Slimefun/Slimefun4/wiki/GlowStone-Boots)
* [Slime Steel Helmet](https://github.com/Slimefun/Slimefun4/wiki/Slime-Steel-Helmet)
* [Slime Steel Chestplate](https://github.com/Slimefun/Slimefun4/wiki/Slime-Steel-Chestplate)
* [Slime Steel Leggings](https://github.com/Slimefun/Slimefun4/wiki/Slime-Steel-Leggings)
* [Slime Steel Boots](https://github.com/Slimefun/Slimefun4/wiki/Slime-Steel-Boots)
* [Farmer Boots](https://github.com/Slimefun/Slimefun4/wiki/Farmer-Boots)
* [Boots of the Stomper](https://github.com/Slimefun/Slimefun4/wiki/Boots-of-the-Stomper)
* [Soulbound Helmet](https://github.com/Slimefun/Slimefun4/wiki/Soulbound-Helmet)
* [Soulbound Chestplate](https://github.com/Slimefun/Slimefun4/wiki/Soulbound-Chestplate)
* [Soulbound Leggings](https://github.com/Slimefun/Slimefun4/wiki/Soulbound-Leggings)
* [Soulbound Boots](https://github.com/Slimefun/Slimefun4/wiki/Soulbound-Boots)
* [Bee Helmet](https://github.com/Slimefun/Slimefun4/wiki/Bee-Helmet)
* [Bee Wings](https://github.com/Slimefun/Slimefun4/wiki/Bee-Wings)
* [Bee Leggings](https://github.com/Slimefun/Slimefun4/wiki/Bee-Leggings)
* [Bee Boots](https://github.com/Slimefun/Slimefun4/wiki/Bee-Boots)
* [Elytra Cap](https://github.com/Slimefun/Slimefun4/wiki/Elytra-Cap)
