This category contains items of various types often used in other recipies. 

## Table of contents
* [Sifted Ore](https://github.com/Slimefun/Slimefun4/wiki/Sifted-Ore)
* [Wheat Flour](https://github.com/Slimefun/Slimefun4/wiki/Wheat-Flour)
* [Steel Plate](https://github.com/Slimefun/Slimefun4/wiki/Steel-Plate)
* [Chain](https://github.com/Slimefun/Slimefun4/wiki/Chain)
* [Hook](https://github.com/Slimefun/Slimefun4/wiki/Hook)
* [Stone Chunk](https://github.com/Slimefun/Slimefun4/wiki/Stone-Chunk)
* [Salt](https://github.com/Slimefun/Slimefun4/wiki/Salt)
* [Heavy Cream](https://github.com/Slimefun/Slimefun4/wiki/Heavy-Cream)
* [Cheese](https://github.com/Slimefun/Slimefun4/wiki/Cheese)
* [Butter](https://github.com/Slimefun/Slimefun4/wiki/Butter)
* [Crushed Ore](https://github.com/Slimefun/Slimefun4/wiki/Crushed-Ore)
* [Pulverized Ore](https://github.com/Slimefun/Slimefun4/wiki/Pulverized-Ore)
* [Pure Oil Cluster](https://github.com/Slimefun/Slimefun4/wiki/Pure-Oil-Cluster)
* [Tiny Pile of Uranium](https://github.com/Slimefun/Slimefun4/wiki/Tiny-Pile-of-Uranium)
* [Small Chunk of Uranium](https://github.com/Slimefun/Slimefun4/wiki/Small-Chunk-of-Uranium)
* [Cloth](https://github.com/Slimefun/Slimefun4/wiki/Cloth)
* [Tin Can](https://github.com/Slimefun/Slimefun4/wiki/Tin-Can)
* [Gold Block (24-Carat)](https://github.com/Slimefun/Slimefun4/wiki/24-Carat-Gold-Block)
* [Reinforced Plate](https://github.com/Slimefun/Slimefun4/wiki/Reinforced-Plate)
* [Duct Tape](https://github.com/Slimefun/Slimefun4/wiki/Duct-Tape)
* [Organic Food](https://github.com/Slimefun/Slimefun4/wiki/Organic-Food)
* [Organic Fertilizer](https://github.com/Slimefun/Slimefun4/wiki/Organic-Fertilizer)
