The technical gadgets are comprised of different electrical related items 
for transport, night vision, flying/fall damage reduction, and basic tools.

## Table of contents
### [Electric JetPacks](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpacks)
* [Electric Jetpack - I](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-I)
* [Electric Jetpack - II](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-II)
* [Electric Jetpack - III](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-III)
* [Electric Jetpack - IV](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-IV)
* [Electric Jetpack - V](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-V)
* [Electric Jetpack - VI](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-VI)
* [Electric Jetpack - VII](https://github.com/Slimefun/Slimefun4/wiki/Electric-Jetpack-VII)
### [Multi Tools](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tools)
* [Multi Tool - I](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-I)
* [Multi Tool - II](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-II)
* [Multi Tool - III](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-III)
* [Multi Tool - IV](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-IV)
* [Multi Tool - V](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-V)
* [Multi Tool - VI](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-VI)
* [Multi Tool - VII](https://github.com/Slimefun/Slimefun4/wiki/Multi-Tool-VII)
### [Jet Boots](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots)
* [Jet-Boots - I](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-I)
* [Jet-Boots - II](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-II)
* [Jet-Boots - III](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-III)
* [Jet-Boots - IV](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-IV)
* [Jet-Boots - V](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-V)
* [Jet-Boots - VI](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-VI)
* [Jet-Boots - VII](https://github.com/Slimefun/Slimefun4/wiki/Jet-Boots-VII)
* [Armored-Jet-Boots](https://github.com/Slimefun/Slimefun4/wiki/Armored-Jet-Boots)
### Other
* [Parachute](https://github.com/Slimefun/Slimefun4/wiki/Parachute)
* [Hologram Projector](https://github.com/Slimefun/Slimefun4/wiki/Hologram-Projector)
* [Solar Helmet](https://github.com/Slimefun/Slimefun4/wiki/Solar-Helmet)
* [Night Vision Goggles](https://github.com/Slimefun/Slimefun4/wiki/Night-Vision-Goggles)
* [Multimeter](https://github.com/Slimefun/Slimefun4/wiki/Multimeter)
